# Generated by Django 3.0 on 2021-01-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_suopplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suopplier',
            new_name='Supplier',
        ),
    ]
