# Generated by Django 3.0 on 2021-01-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20210104_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
