# Generated by Django 3.0 on 2021-01-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20210104_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categor',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='brand_and_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_shipped',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inbound_carrier',
            field=models.CharField(choices=[('UPS', 'UPS'), ('USPS', 'USPS'), ('Fedex', 'Fedex'), ('DHL', 'DHL'), ('Amazon', 'Amazon'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inbound_tracking_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Unpacking Room', 'Unpacking Room'), ('Receiving Room', 'Receiving Room'), ('Small Storage Room A', 'Small Storage Room A'), ('Small Storage Room B', 'Small Storage Room B'), ('Storage Room', 'Storage Room'), ('Packing Room', 'Packing Room'), ('Shipping Room', 'Shipping Room')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='outbound_carrier',
            field=models.CharField(choices=[('UPS', 'UPS'), ('USPS', 'USPS'), ('Fedex', 'Fedex'), ('DHL', 'DHL'), ('Amazon', 'Amazon'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='outbound_tracking_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Level 1: Factory Config', 'Level 1: Factory Config'), ('Level 2: Work in Progress', 'Level 2: Work in Progress'), ('Level 3: Prepare for Shipping', 'Level 3: Prepare for Shipping'), ('LEvel 4: Ready to Ship', 'LEvel 4: Ready to Ship')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='handled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Engineer'),
        ),
    ]
